name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jars
          path: build/libs/*.jar
